// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.domain1;

import com.app.domain1.FirstClass;
import com.app.domain1.FirstClassDataOnDemand;
import com.app.domain1.FirstClassIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FirstClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FirstClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FirstClassIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FirstClassIntegrationTest: @Transactional;
    
    @Autowired
    FirstClassDataOnDemand FirstClassIntegrationTest.dod;
    
    @Test
    public void FirstClassIntegrationTest.testCountFirstClasses() {
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", dod.getRandomFirstClass());
        long count = FirstClass.countFirstClasses();
        Assert.assertTrue("Counter for 'FirstClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FirstClassIntegrationTest.testFindFirstClass() {
        FirstClass obj = dod.getRandomFirstClass();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to provide an identifier", id);
        obj = FirstClass.findFirstClass(id);
        Assert.assertNotNull("Find method for 'FirstClass' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'FirstClass' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FirstClassIntegrationTest.testFindAllFirstClasses() {
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", dod.getRandomFirstClass());
        long count = FirstClass.countFirstClasses();
        Assert.assertTrue("Too expensive to perform a find all test for 'FirstClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<FirstClass> result = FirstClass.findAllFirstClasses();
        Assert.assertNotNull("Find all method for 'FirstClass' illegally returned null", result);
        Assert.assertTrue("Find all method for 'FirstClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FirstClassIntegrationTest.testFindFirstClassEntries() {
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", dod.getRandomFirstClass());
        long count = FirstClass.countFirstClasses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<FirstClass> result = FirstClass.findFirstClassEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'FirstClass' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'FirstClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FirstClassIntegrationTest.testFlush() {
        FirstClass obj = dod.getRandomFirstClass();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to provide an identifier", id);
        obj = FirstClass.findFirstClass(id);
        Assert.assertNotNull("Find method for 'FirstClass' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyFirstClass(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'FirstClass' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirstClassIntegrationTest.testMergeUpdate() {
        FirstClass obj = dod.getRandomFirstClass();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to provide an identifier", id);
        obj = FirstClass.findFirstClass(id);
        boolean modified =  dod.modifyFirstClass(obj);
        Integer currentVersion = obj.getVersion();
        FirstClass merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'FirstClass' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FirstClassIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", dod.getRandomFirstClass());
        FirstClass obj = dod.getNewTransientFirstClass(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'FirstClass' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'FirstClass' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FirstClassIntegrationTest.testRemove() {
        FirstClass obj = dod.getRandomFirstClass();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'FirstClass' failed to provide an identifier", id);
        obj = FirstClass.findFirstClass(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'FirstClass' with identifier '" + id + "'", FirstClass.findFirstClass(id));
    }
    
}
