// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.domain1;

import com.app.domain1.FirstClass;

privileged aspect FirstClass_Roo_JavaBean {
    
    public String FirstClass.getName1() {
        return this.name1;
    }
    
    public void FirstClass.setName1(String name1) {
        this.name1 = name1;
    }
    
}
