// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.domain1;

import com.app.domain1.FirstClass;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FirstClass_Roo_Configurable {
    
    declare @type: FirstClass: @Configurable;
    
}
